name: Create Release Notes Preview

on:
  pull_request:
    types: [ "opened", "reopened" ]
    
permissions:
  contents: read
  
jobs:
  release_note:
    permissions:
        contents: write
        pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Generate release notes
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-name: workflows/release-notes.yml
          template: |
            ## What’s Changed

            $CHANGES
